const scents = [
  'Acid',
  'Alcohol',
  'Almond',
  'Ammonia',
  'Animal',
  'Baby',
  'Balsamic',
  'Banana',
  'Barnyard',
  'Bitter',
  'Bread dough',
  'Brine',
  'Burnt hair',
  'Burnt plastic',
  'Burnt rubber',
  'Burnt sugar',
  'Burnt toast',
  'Caramel',
  'Cedarwood',
  'Cherry',
  'Chlorine',
  'Chocolate',
  'Cigarette ash',
  'Coffee',
  'Cologne',
  'Cookies',
  'Coppery',
  'Cut grass',
  'Damp',
  'Dog breath',
  'Dumpster',
  'Earth',
  'Element',
  'Exhaust',
  'Fish',
  'Food',
  'Formaldehyde',
  'Garlic',
  'Gasoline',
  'Ginger',
  'Gunpowder',
  'Hamster cage',
  'Hay',
  'Herbal',
  'Honey',
  'Hops',
  'Incense',
  'Leather',
  'Lemon',
  'Licorice',
  'Lysol',
  'Manure',
  'Medicinal',
  'Mildew',
  'Mint',
  'Mould',
  'Musk',
  'Nutmeg',
  'Old books',
  'Old socks',
  'Olive oil',
  'Onion',
  'Orange',
  'Ozone',
  'Paint',
  'Peanut butter',
  'Peat moss',
  'Pine',
  'Popcorn',
  'Rain',
  'Resinous',
  'Rose',
  'Rotten eggs',
  'Rotten meat',
  'Rotting fruit',
  'Seaweed',
  'Sewer',
  'Skunk',
  'Sour milk',
  'Spicy',
  'Spruce',
  'Stagnant',
  'Stale beer',
  'Stinky cheese',
  'Sulfur',
  'Sweat',
  'Taste',
  'Tea',
  'Thyme',
  'Tobacco',
  'Turpentine',
  'Vanilla',
  'Vinegar',
  'Violets',
  'Vomit',
  'Wet cardboard',
  'Wet dog',
  'Wood smoke',
]

const effects = [
  'Age',
  'All languages',
  'Alter body',
  'Alter face',
  'Alter voice',
  'Armour',
  'Beast-speech',
  'Bird-speech',
  'Breathlessness',
  'Claws',
  'Cold-proof',
  'Courage',
  'Cure disease',
  'Cure poison',
  'Cure wounds',
  'Dark vision',
  'Dead-speech',
  'Delusion (p. 30)', // Retaining original note for clarity
  'Effect (p. 28)', // Retaining original note for clarity
  'Elasticity',
  'Elem. form (p. 29)', // Retaining original note for clarity
  'Extra arms',
  'False death',
  'Fear',
  'Fire form',
  'Fish-speech',
  'Flight',
  'Forgetfulness',
  'Friendship',
  'Growth',
  'Grub-speech',
  'Hate',
  'Healing',
  'Heat-proof',
  'Hunger-proof',
  'Ice form',
  'Illumination',
  'Intangibility',
  'Invisibility',
  'Invulnerability',
  'Iron stomach',
  'Jumping',
  'Lightning form',
  'Lightning-proof',
  'Love',
  'Lycanthropy',
  'Magic-proof',
  'Magnetism',
  'Magma form',
  'Mammal-speech',
  'Memory',
  'Metal form',
  'Metal-speech',
  'Metal-proof',
  'Might',
  'Mind reading',
  'Mind-speech',
  'Ooze form',
  'Paranoia',
  'Plant-speech',
  'Poison-proof',
  'Rage',
  'Sense danger',
  'Sense direction',
  'Sense evil',
  'Sense gold',
  'Sense heat',
  'Sense illusion',
  'Sense lies',
  'Sense magic',
  'Sense undead',
  'Shape-shifting',
  'Shrinking',
  'Sleep',
  'Sleepnessness',
  'Smoke form',
  'Sniffing',
  'Sovereign acid',
  'Sovereign glue',
  'Sovereign grease',
  'Sovereign poison',
  'Speed',
  'Spines',
  'Stinger',
  'Stone-speech',
  'Swimming',
  'Telekinesis',
  'Thought-sending',
  'Undeath',
  'Vampirism',
  'Ventriloquism',
  'Vision',
  'Wall-crawling',
  'Water-breathing',
  'Water-walking',
  'Web-slinging',
  'X-ray vision',
  'Youth',
  'Ages backwards',
  'Head swells',
  'Ages faster',
  'Horns',
  'Invisible head',
  'Jelly arms',
  'Legs grow',
  'Long tongue',
  'Lose d20 inches',
  'Antennae',
  'One arm',
  'Antlers',
  'One eye',
  'Arms grow',
  'One leg',
  'Bat wings',
  'Beak',
  'Bird wings',
  'Pig snout',
  'Bleeds acid',
  'Chameleon eyes',
  'Rat tail',
  'Claws',
  'Scales',
  'Crystal growth',
  'Scorpion tail',
  'Drooling',
  'Shaggy fur',
  'Duck bill',
  'Shell',
  'Ears grow',
  'Skin boils',
  'Skin hardens',
  'Skin pattern',
  'Skin sags',
  'Skin shedding',
  'Emits fumes',
  'Smoke breath',
  'Excretes ooze',
  'Snake hair',
  'Extra arms',
  'Extra eyes',
  'Extra fingers',
  'Spines',
  'Extra heads',
  'Spinnerets',
  'Extra legs',
  'Suction cups',
  'Eye stalks',
  'Sweats blood',
  'Eyes grow',
  'Tentacles',
  'Fangs',
  'Feathers',
  'Totally numb',
  'Feet swell',
  'Translucent skin',
  'Fins',
  'Transparent skin',
  'Fly eyes',
  'Tusks',
  'Fungal growth',
  'Two faces',
  'Gain d20 inches',
  'Warts',
  'Gills',
  'Webbed hands',
  'Hair growth',
  'Weight doubles',
  'Hair loss',
  'Weight halves',
  'Hands swell',
  'Wooly',
]

const textures = [
  'Aerated',
  'Battery',
  'Blended',
  'Brackish',
  'Bubbling',
  'Buttery',
  'Caramelized',
  'Chalky',
  'Chilled',
  'Chunky',
  'Churning',
  'Clotted',
  'Coagulated',
  'Condensed',
  'Congealed',
  'Cool',
  'Creamy',
  'Crystalized',
  'Curdled',
  'Dregs',
  'Effervescent',
  'Filmy',
  'Fizzing',
  'Flakes',
  'Foaming',
  'Foggy',
  'Frigid',
  'Frothy',
  'Frosty',
  'Gelatinous',
  'Glimmering',
  'Gloppy',
  'Glowing',
  'Gluey',
  'Grainy',
  'Greasy',
  'Gritty',
  'Grounds',
  'Gummy',
  'Gunky',
  'Gurgling',
  'Hissing',
  'Humming',
  'Ichorous',
  'Icy',
  'Jellied',
  'Living',
  'Lukewarm',
  'Lumpy',
  'Mashed',
  'Metallic',
  'Moist',
  'Moving',
  'Muddy',
  'Murky',
  'Mushy',
  'Oily',
  'Oozy',
  'Powdery',
  'Pudding',
  'Pulpy',
  'Pulsing',
  'Pureed',
  'Quicksilver',
  'Reflective',
  'Rippling',
  'Roiling',
  'Sandy',
  'Sappy',
  'Scalding',
  'Scummy film',
  'Sediment',
  'Shining',
  'Silty',
  'Shimmering',
  'Sizzling',
  'Slimy',
  'Slushy',
  'Smoking',
  'Smoky',
  'Soapy',
  'Sparkling',
  'Steaming',
  'Sticky',
  'Swirling',
  'Syrupy',
  'Tarry',
  'Thin',
  'Throbbing',
  'Trembling',
  'Turbulent',
  'Vibrating',
  'Viscid',
  'Viscous',
  'Warm',
  'Watery',
  'Whirling',
  'Whistling',
]

const tastes = [
  'Absinthe',
  'Allspice',
  'Almond',
  'Ammonia',
  'Asparagus',
  'Basil',
  'Beer',
  'Berries',
  'Black currant',
  'Blackberry',
  'Blood',
  'Butter',
  'Camphor',
  'Candy',
  'Caramel',
  'Cardamom',
  'Cherry',
  'Chili pepper',
  'Chives',
  'Chocolate',
  'Cinnamon',
  'Cloves',
  'Coconut',
  'Coffee',
  'Copper',
  'Cranberry',
  'Crude oil',
  'Cucumber',
  'Cumin',
  'Curry',
  'Dates',
  'Elderberry',
  'Figs',
  'Flowers',
  'Garlic',
  'Ginger',
  'Gooseberry',
  'Grapefruit',
  'Grass',
  'Herbs',
  'Honey',
  'Honeysuckle',
  'Horseradish',
  'Huckleberry',
  'Hyacinth',
  'Leather',
  'Lemon',
  'Lemongrass',
  'Licorice',
  'Lime',
  'Loam',
  'Maple syrup',
  'Mead',
  'Milk',
  'Mineral',
  'Mint',
  'Mud',
  'Mustard',
  'Nutmeg',
  'Oak',
  'Olive oil',
  'Onion',
  'Orange',
  'Oregano',
  'Peach',
  'Pears',
  'Pepper',
  'Phlegm',
  'Pickle juice',
  'Pine',
  'Pistachios',
  'Plum',
  'Pumpkin',
  'Quince',
  'Rhubarb',
  'Roast duck',
  'Rose',
  'Rosemary',
  'Rust',
  'Saffron',
  'Sage',
  'Salt water',
  'Soap',
  'Soursop',
  'Spearmint',
  'Sulphur',
  'Tamarind',
  'Tea',
  'Tears',
  'Thyme',
  'Tobacco',
  'Vanilla',
  'Walnuts',
  'Whiskey',
  'Wine',
  'Wintergreen',
  'Wormwood',
]

const colours = [
  'Acid green',
  'Alabaster',
  'Amber',
  'Amethyst',
  'Apricot',
  'Aquamarine',
  'Asparagus',
  'Auburn',
  'Avocado',
  'Aureolin',
  'Azure',
  'Baby blue',
  'Beige',
  'Bone',
  'Bottle green',
  'Bronze',
  'Bubblegum',
  'Carmine',
  'Carrot',
  'Celadon',
  'Cerise',
  'Cerulean',
  'Champagne',
  'Charcoal',
  'Chartreuse',
  'Chestnut',
  'Cinnamon',
  'Colourless',
  'Coppery',
  'Coral pink',
  'Creamy',
  'Crimson',
  'Cyan',
  'Dove grey',
  'Dun',
  'Eggshell',
  'Electric blue',
  'Emerald',
  'Flesh',
  'Fuchsia',
  'Fuligin',
  'Golden',
  'Grape juice',
  'Heliotrope',
  'Ice blue',
  'Indigo',
  'Inky',
  'Invisible',
  'Ivory',
  'Kelly green',
  'Lavender',
  'Lilac',
  'Lime',
  'Magenta',
  'Mahogany',
  'Maroon',
  'Mauve',
  'Milk white',
  'Moss green',
  'Mustard',
  'Ochre',
  'Olive',
  'Opalescent',
  'Oxblood',
  'Pea green',
  'Peach',
  'Peacock blue',
  'Pearl',
  'Periwinkle',
  'Pine green',
  'Plum',
  'Primrose',
  'Pumpkin',
  'Rainbow',
  'Rose',
  'Ruby',
  'Russet',
  'Rusty',
  'Saffron',
  'Salmon',
  'Sapphire',
  'Scarlet',
  'Sepia',
  'Shocking pink',
  'Silver',
  'Slate blue',
  'Smokey grey',
  'Tangerine',
  'Teal',
  'Terracotta',
  'Titian red',
  'Tomato',
  'Turquoise',
  'Tyrian',
  'Ultramarine',
  'Umber',
  'Verdigris',
  'Vermilion',
  'Violet',
  'Viridian',
]

function getRandom(arr) {
  return arr[Math.floor(Math.random() * arr.length)]
}

function toTitleCase(str) {
  // This regex matches the first character of the string OR
  // any character that is immediately preceded by a space, hyphen, or apostrophe.
  // The 'g' flag ensures all occurrences are matched.
  return str.replace(/(?:^|\s|-|')\S/g, function (a) {
    return a.toUpperCase()
  })
}

export function getPotion() {
  const texture = getRandom(textures)
  const taste = getRandom(tastes)
  const colour = getRandom(colours)
  const effect = getRandom(effects)

  // Generate a random number between 1 and 6 for variety
  const d6Roll = Math.floor(Math.random() * 6) + 1

  let name = ''

  switch (d6Roll) {
    case 1:
      // Simple combination: "Liquid <Colour>" or "<Texture> Potion"
      if (Math.random() < 0.5) {
        // 50% chance for a more descriptive prefix
        name = `The ${colour} ${texture} Potion`
      } else {
        name = `A Potion of ${effect}`
      }
      break
    case 2:
      // Focusing on taste and effect: "Potion of <Taste> <Effect>"
      name = `Potion of ${taste} ${effect}`
      break
    case 3:
      // Highlighting texture and colour: "<Texture> <Colour> Brew"
      name = `The ${texture} ${colour} Brew`
      break
    case 4:
      // Combining two sensory inputs and an effect: "<Colour>, <Taste> Elixir of <Effect>"
      name = `The ${colour}, ${taste} Elixir of ${effect}`
      break
    case 5:
      // A more evocative, strange name: "Draught of the <Texture> <Effect>" or "A <Colour> Draught of <Effect>"
      if (Math.random() < 0.5) {
        name = `The Draught of ${texture} ${effect}`
      } else {
        name = `A ${colour} Draught of ${effect}`
      }
      break
    case 6:
      // A grander, possibly ominous name: "The <Effect> Concoction of <Taste> and <Texture>"
      name = `The ${effect} Concoction of ${taste} and ${texture}`
      break
    default:
      name = 'Unknown Potion' // Should not be reached
      break
  }

  // A final touch for some fun projects and clever names
  if (Math.random() < 0.1) {
    // 10% chance for a really unique name
    const prefix = getRandom(['Whisper of', 'Tears of the', 'Glimmer of', 'Breath of', 'Essence of the'])
    const suffix = getRandom(['Dream-Eater', 'Void-Gazer', 'Grim Harvest', 'Star-Whisperer', 'Reality Bender'])
    name = `${prefix} ${colour} ${suffix}`
  }

  // Clean up any remaining page references in the generated string
  name = name.replace(/\(p\. \d+\)/g, '').trim()

  // Apply title case to the entire generated name
  name = toTitleCase(name)

  return name
}

export async function getPotionDescription(potionName) {
  const response = await fetch('ai/api/potion-description', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ potionName: potionName }),
  })

  let { description } = await response.json()

  // description = description.replace(/^"|"$/g, '')

  return description
}